/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('processing' | 'completed' | 'cancelled' | 'refunded') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    posts: Post;
    categories: Category;
    'post-categories': PostCategory;
    brands: Brand;
    tags: Tag;
    coupons: Coupon;
    markets: Market;
    media: Media;
    forms: Form;
    'form-submissions': FormSubmission;
    addresses: Address;
    variants: Variant;
    variantTypes: VariantType;
    variantOptions: VariantOption;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      orders: 'orders';
      cart: 'carts';
      addresses: 'addresses';
    };
    variantTypes: {
      options: 'variantOptions';
    };
    products: {
      variants: 'variants';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'post-categories': PostCategoriesSelect<false> | PostCategoriesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    markets: MarketsSelect<false> | MarketsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    variantTypes: VariantTypesSelect<false> | VariantTypesSelect<true>;
    variantOptions: VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('sr' | 'en') | ('sr' | 'en')[];
  globals: {
    header: Header;
    footer: Footer;
    clients: Client;
    settings: Setting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: 'sr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers?: User;
      orders: Order;
      products: Product;
      transactions: Transaction;
      variantOptions: VariantOption;
      variants: Variant;
      variantTypes: VariantType;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles?: ('admin' | 'customer')[] | null;
  orders?: {
    docs?: (number | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  cart?: {
    docs?: (number | Cart)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  addresses?: {
    docs?: (number | Address)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  customer?: (number | null) | User;
  customerEmail?: string | null;
  transactions?: (number | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: 'USD' | null;
  accessToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: number | Media;
        variantOption?: (number | VariantOption)[] | null;
        id?: string | null;
      }[]
    | null;
  layout?:
    | (
        | AmbassadorBlock
        | BrandStoryBlock
        | BannerBlock
        | CallToActionBlock
        | ContentBlock
        | MissionBlock
        | WhyUsBlock
        | ServicesBlock
        | ProjectsPreviewBlock
        | TestimonialsBlock
        | ClientLogosBlock
        | MediaBlock
        | CarouselBlock
        | ThreeItemGridBlock
        | ArchiveBlock
        | CodeBlock
        | ContactInfoBlock
        | FormBlock
        | QuoteBlock
        | FAQBlock
        | StatsBlock
        | VideoBlock
        | SpacerBlock
      )[]
    | null;
  badges?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  specifications?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  price: number;
  salePrice?: number | null;
  saleStartDate?: string | null;
  saleEndDate?: string | null;
  inventory?: number | null;
  enableVariants?: boolean | null;
  variantTypes?: (number | VariantType)[] | null;
  variants?: {
    docs?: (number | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  priceInUSDEnabled?: boolean | null;
  priceInUSD?: number | null;
  relatedProducts?: (number | Product)[] | null;
  brand?: (number | null) | Brand;
  tags?: (number | Tag)[] | null;
  upsell?: (number | Product)[] | null;
  crossSell?: (number | Product)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  categories?: (number | Category)[] | null;
  visibility?: ('catalog' | 'catalogOnly' | 'searchOnly' | 'hidden') | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions".
 */
export interface VariantOption {
  id: number;
  _variantOptions_options_order?: string | null;
  variantType: number | VariantType;
  label: string;
  /**
   * should be defaulted or dynamic based on label
   */
  value: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes".
 */
export interface VariantType {
  id: number;
  label: string;
  name: string;
  options?: {
    docs?: (number | VariantOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AmbassadorBlock".
 */
export interface AmbassadorBlock {
  layout?: ('media-right' | 'media-left') | null;
  eyebrow?: string | null;
  heading: string;
  role?: string | null;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  video: {
    platform?: ('youtube' | 'vimeo' | 'direct') | null;
    url: string;
    /**
     * Optional — shown as fallback if video cannot be embedded
     */
    thumbnail?: (number | null) | Media;
  };
  /**
   * Optional button below the description
   */
  cta?: {
    label?: string | null;
    url?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'ambassador';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandStoryBlock".
 */
export interface BrandStoryBlock {
  layout?: ('image-right' | 'image-left') | null;
  /**
   * Cover crops the image to fill the frame. Contain shows the full image on a dark background — ideal for product shots.
   */
  imageFit?: ('cover' | 'contain') | null;
  eyebrow?: string | null;
  heading: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (number | null) | Media;
  /**
   * Optional YouTube URL — if set, a video embed replaces the image (e.g. CEO/company video).
   */
  videoUrl?: string | null;
  /**
   * Up to 4 key figures displayed in a 2×2 grid
   */
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional button below the text
   */
  cta?: {
    label?: string | null;
    url?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'brandStory';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'products';
                value: number | Product;
              } | null)
            | ({
                relationTo: 'categories';
                value: number | Category;
              } | null)
            | ({
                relationTo: 'brands';
                value: number | Brand;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'post-categories';
                value: number | PostCategory;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  publishedOn?: string | null;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    /**
     * Mala oznaka iznad naslova (npr. „Premium kapije i ograde").
     */
    eyebrow?: string | null;
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'products';
                  value: number | Product;
                } | null)
              | ({
                  relationTo: 'categories';
                  value: number | Category;
                } | null)
              | ({
                  relationTo: 'brands';
                  value: number | Brand;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null)
              | ({
                  relationTo: 'post-categories';
                  value: number | PostCategory;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
    /**
     * Standardno: jak tamni gradijent, slika u pozadini iza teksta. Full cover: slika ispunjava ceo hero i dominira, blaži preliv samo radi čitljivosti.
     */
    mediaStyle?: ('standard' | 'cover') | null;
    /**
     * Brojevi u dnu hero-a (npr. 700+ / klijenata).
     */
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Kratke garancije (npr. Besplatno merenje).
     */
    trust?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  layout?:
    | (
        | AmbassadorBlock
        | BrandStoryBlock
        | BannerBlock
        | CallToActionBlock
        | ContentBlock
        | MissionBlock
        | WhyUsBlock
        | ServicesBlock
        | ProjectsPreviewBlock
        | TestimonialsBlock
        | ClientLogosBlock
        | MediaBlock
        | CarouselBlock
        | ThreeItemGridBlock
        | ArchiveBlock
        | CodeBlock
        | ContactInfoBlock
        | FormBlock
        | QuoteBlock
        | FAQBlock
        | StatsBlock
        | VideoBlock
        | SpacerBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Optional landing page content for this category.
   */
  content?:
    | (
        | AmbassadorBlock
        | BrandStoryBlock
        | BannerBlock
        | CallToActionBlock
        | ContentBlock
        | MissionBlock
        | WhyUsBlock
        | ServicesBlock
        | ProjectsPreviewBlock
        | TestimonialsBlock
        | ClientLogosBlock
        | MediaBlock
        | CarouselBlock
        | ThreeItemGridBlock
        | ArchiveBlock
        | CodeBlock
        | ContactInfoBlock
        | FormBlock
        | QuoteBlock
        | FAQBlock
        | StatsBlock
        | VideoBlock
        | SpacerBlock
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'products';
                value: number | Product;
              } | null)
            | ({
                relationTo: 'categories';
                value: number | Category;
              } | null)
            | ({
                relationTo: 'brands';
                value: number | Brand;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'post-categories';
                value: number | PostCategory;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  logo?: (number | null) | Media;
  description?: string | null;
  /**
   * Optional landing page content for this brand.
   */
  content?:
    | (
        | AmbassadorBlock
        | BrandStoryBlock
        | BannerBlock
        | CallToActionBlock
        | ContentBlock
        | MissionBlock
        | WhyUsBlock
        | ServicesBlock
        | ProjectsPreviewBlock
        | TestimonialsBlock
        | ClientLogosBlock
        | MediaBlock
        | CarouselBlock
        | ThreeItemGridBlock
        | ArchiveBlock
        | CodeBlock
        | ContactInfoBlock
        | FormBlock
        | QuoteBlock
        | FAQBlock
        | StatsBlock
        | VideoBlock
        | SpacerBlock
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MissionBlock".
 */
export interface MissionBlock {
  eyebrow?: string | null;
  heading?: string | null;
  /**
   * Glavna izjava o misiji (jedan do dva pasusa).
   */
  statement?: string | null;
  /**
   * Stubovi / vrednosti (ikona + naslov + opis).
   */
  values?:
    | {
        icon?: ('shield' | 'sparkles' | 'clock' | 'wrench' | 'award' | 'users' | 'check') | null;
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mission';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyUsBlock".
 */
export interface WhyUsBlock {
  eyebrow?: string | null;
  heading?: string | null;
  items?:
    | {
        icon?: ('check' | 'shield' | 'ruler' | 'truck' | 'wrench' | 'award' | 'clock' | 'sparkles' | 'users') | null;
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'whyUs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock".
 */
export interface ServicesBlock {
  eyebrow?: string | null;
  heading?: string | null;
  intro?: string | null;
  source?: ('auto' | 'manual') | null;
  items?:
    | {
        image?: (number | null) | Media;
        title: string;
        href?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'services';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectsPreviewBlock".
 */
export interface ProjectsPreviewBlock {
  eyebrow?: string | null;
  heading?: string | null;
  intro?: string | null;
  ctaLabel?: string | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'projectsPreview';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  eyebrow?: string | null;
  heading?: string | null;
  intro?: string | null;
  items?:
    | {
        text: string;
        author: string;
        role?: string | null;
        /**
         * Logo firme ili foto (opciono).
         */
        avatar?: (number | null) | Media;
        rating?: ('5' | '4' | '3') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClientLogosBlock".
 */
export interface ClientLogosBlock {
  heading?: string | null;
  logos?:
    | {
        image: number | Media;
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'clientLogos';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocsTotal?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock".
 */
export interface ThreeItemGridBlock {
  products?: (number | Product)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'threeItemGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactInfoBlock".
 */
export interface ContactInfoBlock {
  heading?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  email?: string | null;
  address?: string | null;
  /**
   * Google Maps link za adresu (opciono).
   */
  mapUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactInfo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  /**
   * Ako je popunjeno, Google mapa za ovu adresu se prikazuje pored forme.
   */
  mapAddress?: string | null;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock".
 */
export interface QuoteBlock {
  text: string;
  author?: string | null;
  role?: string | null;
  avatar?: (number | null) | Media;
  rating?: ('5' | '4' | '3') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  heading?: string | null;
  items: {
    question: string;
    answer: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  label?: string | null;
  heading?: string | null;
  items?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock".
 */
export interface VideoBlock {
  platform: 'youtube' | 'vimeo' | 'direct';
  autoplay?: boolean | null;
  url: string;
  caption?: string | null;
  thumbnail?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerBlock".
 */
export interface SpacerBlock {
  size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  showDivider?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'spacer';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  publishedOn?: string | null;
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  layout?:
    | (
        | AmbassadorBlock
        | BrandStoryBlock
        | BannerBlock
        | CallToActionBlock
        | ContentBlock
        | MissionBlock
        | WhyUsBlock
        | ServicesBlock
        | ProjectsPreviewBlock
        | TestimonialsBlock
        | ClientLogosBlock
        | MediaBlock
        | CarouselBlock
        | ThreeItemGridBlock
        | ArchiveBlock
        | CodeBlock
        | ContactInfoBlock
        | FormBlock
        | QuoteBlock
        | FAQBlock
        | StatsBlock
        | VideoBlock
        | SpacerBlock
      )[]
    | null;
  categories: (number | PostCategory)[];
  relatedPosts?: (number | Post)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories".
 */
export interface PostCategory {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Optional landing page content for this blog category.
   */
  content?:
    | (
        | AmbassadorBlock
        | BrandStoryBlock
        | BannerBlock
        | CallToActionBlock
        | ContentBlock
        | MissionBlock
        | WhyUsBlock
        | ServicesBlock
        | ProjectsPreviewBlock
        | TestimonialsBlock
        | ClientLogosBlock
        | MediaBlock
        | CarouselBlock
        | ThreeItemGridBlock
        | ArchiveBlock
        | CodeBlock
        | ContactInfoBlock
        | FormBlock
        | QuoteBlock
        | FAQBlock
        | StatsBlock
        | VideoBlock
        | SpacerBlock
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  /**
   * Used for administrative purposes, not shown to customers. This is populated by default.
   */
  title?: string | null;
  product: number | Product;
  options: (number | VariantOption)[];
  inventory?: number | null;
  priceInUSDEnabled?: boolean | null;
  priceInUSD?: number | null;
  /**
   * Cena ove varijacije u RSD (dinari, integer).
   */
  price?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  paymentMethod?: 'stripe' | null;
  stripe?: {
    customerID?: string | null;
    paymentIntentID?: string | null;
  };
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (number | null) | User;
  customerEmail?: string | null;
  order?: (number | null) | Order;
  cart?: (number | null) | Cart;
  amount?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (number | null) | User;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  customer?: (number | null) | User;
  title?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country:
    | 'US'
    | 'GB'
    | 'CA'
    | 'AU'
    | 'AT'
    | 'BE'
    | 'BR'
    | 'BG'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'EE'
    | 'FI'
    | 'FR'
    | 'DE'
    | 'GR'
    | 'HK'
    | 'HU'
    | 'IN'
    | 'IE'
    | 'IT'
    | 'JP'
    | 'LV'
    | 'LT'
    | 'LU'
    | 'MY'
    | 'MT'
    | 'MX'
    | 'NL'
    | 'NZ'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'ES'
    | 'SE'
    | 'CH';
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  code: string;
  active?: boolean | null;
  type: 'percentage' | 'fixed';
  value: number;
  minimumOrderAmount?: number | null;
  usageLimit?: number | null;
  startsAt?: string | null;
  endsAt?: string | null;
  usageCount?: number | null;
  targetProducts?: (number | Product)[] | null;
  targetCategories?: (number | Category)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Markets / distributors displayed in the Country Gate popup on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets".
 */
export interface Market {
  id: number;
  label: string;
  flag: string;
  active?: boolean | null;
  /**
   * ISO 3166-1 alpha-2 codes separated by commas. e.g. RS or HR,AT,DE,FR
   */
  countryCode: string;
  url: string;
  /**
   * Lower number = displayed first. Recommended markets should be placed at the top.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'post-categories';
        value: number | PostCategory;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'markets';
        value: number | Market;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'variantTypes';
        value: number | VariantType;
      } | null)
    | ({
        relationTo: 'variantOptions';
        value: number | VariantOption;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  orders?: T;
  cart?: T;
  addresses?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  publishedOn?: T;
  hero?:
    | T
    | {
        type?: T;
        eyebrow?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
        mediaStyle?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        trust?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  layout?:
    | T
    | {
        ambassador?: T | AmbassadorBlockSelect<T>;
        brandStory?: T | BrandStoryBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mission?: T | MissionBlockSelect<T>;
        whyUs?: T | WhyUsBlockSelect<T>;
        services?: T | ServicesBlockSelect<T>;
        projectsPreview?: T | ProjectsPreviewBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        clientLogos?: T | ClientLogosBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        code?: T | CodeBlockSelect<T>;
        contactInfo?: T | ContactInfoBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        spacer?: T | SpacerBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AmbassadorBlock_select".
 */
export interface AmbassadorBlockSelect<T extends boolean = true> {
  layout?: T;
  eyebrow?: T;
  heading?: T;
  role?: T;
  description?: T;
  video?:
    | T
    | {
        platform?: T;
        url?: T;
        thumbnail?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandStoryBlock_select".
 */
export interface BrandStoryBlockSelect<T extends boolean = true> {
  layout?: T;
  imageFit?: T;
  eyebrow?: T;
  heading?: T;
  description?: T;
  image?: T;
  videoUrl?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MissionBlock_select".
 */
export interface MissionBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  statement?: T;
  values?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyUsBlock_select".
 */
export interface WhyUsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock_select".
 */
export interface ServicesBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  source?: T;
  items?:
    | T
    | {
        image?: T;
        title?: T;
        href?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectsPreviewBlock_select".
 */
export interface ProjectsPreviewBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  ctaLabel?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  items?:
    | T
    | {
        text?: T;
        author?: T;
        role?: T;
        avatar?: T;
        rating?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClientLogosBlock_select".
 */
export interface ClientLogosBlockSelect<T extends boolean = true> {
  heading?: T;
  logos?:
    | T
    | {
        image?: T;
        name?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  populatedDocs?: T;
  populatedDocsTotal?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock_select".
 */
export interface ThreeItemGridBlockSelect<T extends boolean = true> {
  products?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock_select".
 */
export interface CodeBlockSelect<T extends boolean = true> {
  language?: T;
  code?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactInfoBlock_select".
 */
export interface ContactInfoBlockSelect<T extends boolean = true> {
  heading?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  address?: T;
  mapUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  mapAddress?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock_select".
 */
export interface QuoteBlockSelect<T extends boolean = true> {
  text?: T;
  author?: T;
  role?: T;
  avatar?: T;
  rating?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  items?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock_select".
 */
export interface VideoBlockSelect<T extends boolean = true> {
  platform?: T;
  autoplay?: T;
  url?: T;
  caption?: T;
  thumbnail?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerBlock_select".
 */
export interface SpacerBlockSelect<T extends boolean = true> {
  size?: T;
  showDivider?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  publishedOn?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  layout?:
    | T
    | {
        ambassador?: T | AmbassadorBlockSelect<T>;
        brandStory?: T | BrandStoryBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mission?: T | MissionBlockSelect<T>;
        whyUs?: T | WhyUsBlockSelect<T>;
        services?: T | ServicesBlockSelect<T>;
        projectsPreview?: T | ProjectsPreviewBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        clientLogos?: T | ClientLogosBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        code?: T | CodeBlockSelect<T>;
        contactInfo?: T | ContactInfoBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        spacer?: T | SpacerBlockSelect<T>;
      };
  categories?: T;
  relatedPosts?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  description?: T;
  image?: T;
  content?:
    | T
    | {
        ambassador?: T | AmbassadorBlockSelect<T>;
        brandStory?: T | BrandStoryBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mission?: T | MissionBlockSelect<T>;
        whyUs?: T | WhyUsBlockSelect<T>;
        services?: T | ServicesBlockSelect<T>;
        projectsPreview?: T | ProjectsPreviewBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        clientLogos?: T | ClientLogosBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        code?: T | CodeBlockSelect<T>;
        contactInfo?: T | ContactInfoBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        spacer?: T | SpacerBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories_select".
 */
export interface PostCategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  image?: T;
  content?:
    | T
    | {
        ambassador?: T | AmbassadorBlockSelect<T>;
        brandStory?: T | BrandStoryBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mission?: T | MissionBlockSelect<T>;
        whyUs?: T | WhyUsBlockSelect<T>;
        services?: T | ServicesBlockSelect<T>;
        projectsPreview?: T | ProjectsPreviewBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        clientLogos?: T | ClientLogosBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        code?: T | CodeBlockSelect<T>;
        contactInfo?: T | ContactInfoBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        spacer?: T | SpacerBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  logo?: T;
  description?: T;
  content?:
    | T
    | {
        ambassador?: T | AmbassadorBlockSelect<T>;
        brandStory?: T | BrandStoryBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mission?: T | MissionBlockSelect<T>;
        whyUs?: T | WhyUsBlockSelect<T>;
        services?: T | ServicesBlockSelect<T>;
        projectsPreview?: T | ProjectsPreviewBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        clientLogos?: T | ClientLogosBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        code?: T | CodeBlockSelect<T>;
        contactInfo?: T | ContactInfoBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        spacer?: T | SpacerBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  active?: T;
  type?: T;
  value?: T;
  minimumOrderAmount?: T;
  usageLimit?: T;
  startsAt?: T;
  endsAt?: T;
  usageCount?: T;
  targetProducts?: T;
  targetCategories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets_select".
 */
export interface MarketsSelect<T extends boolean = true> {
  label?: T;
  flag?: T;
  active?: T;
  countryCode?: T;
  url?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  options?: T;
  inventory?: T;
  priceInUSDEnabled?: T;
  priceInUSD?: T;
  price?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  _variantOptions_options_order?: T;
  variantType?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  gallery?:
    | T
    | {
        image?: T;
        variantOption?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        ambassador?: T | AmbassadorBlockSelect<T>;
        brandStory?: T | BrandStoryBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mission?: T | MissionBlockSelect<T>;
        whyUs?: T | WhyUsBlockSelect<T>;
        services?: T | ServicesBlockSelect<T>;
        projectsPreview?: T | ProjectsPreviewBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        clientLogos?: T | ClientLogosBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        code?: T | CodeBlockSelect<T>;
        contactInfo?: T | ContactInfoBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        spacer?: T | SpacerBlockSelect<T>;
      };
  badges?:
    | T
    | {
        label?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        label?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  price?: T;
  salePrice?: T;
  saleStartDate?: T;
  saleEndDate?: T;
  inventory?: T;
  enableVariants?: T;
  variantTypes?: T;
  variants?: T;
  priceInUSDEnabled?: T;
  priceInUSD?: T;
  relatedProducts?: T;
  brand?: T;
  tags?: T;
  upsell?: T;
  crossSell?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  categories?: T;
  visibility?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  accessToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  paymentMethod?: T;
  stripe?:
    | T
    | {
        customerID?: T;
        paymentIntentID?: T;
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  siteName?: string | null;
  logo?: (number | null) | Media;
  topBar?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'products';
                value: number | Product;
              } | null)
            | ({
                relationTo: 'categories';
                value: number | Category;
              } | null)
            | ({
                relationTo: 'brands';
                value: number | Brand;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'post-categories';
                value: number | PostCategory;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'products';
                value: number | Product;
              } | null)
            | ({
                relationTo: 'categories';
                value: number | Category;
              } | null)
            | ({
                relationTo: 'brands';
                value: number | Brand;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'post-categories';
                value: number | PostCategory;
              } | null);
          url?: string | null;
          label: string;
        };
        subItems?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'products';
                      value: number | Product;
                    } | null)
                  | ({
                      relationTo: 'categories';
                      value: number | Category;
                    } | null)
                  | ({
                      relationTo: 'brands';
                      value: number | Brand;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null)
                  | ({
                      relationTo: 'post-categories';
                      value: number | PostCategory;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  promoBanner: {
    enabled?: boolean | null;
    text?: string | null;
    link: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'products';
            value: number | Product;
          } | null)
        | ({
            relationTo: 'categories';
            value: number | Category;
          } | null)
        | ({
            relationTo: 'brands';
            value: number | Brand;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null)
        | ({
            relationTo: 'post-categories';
            value: number | PostCategory;
          } | null);
      url?: string | null;
      label: string;
    };
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Logo koji se prikazuje u footeru. Preporučena veličina: 160×40px.
   */
  logo?: (number | null) | Media;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'products';
                value: number | Product;
              } | null)
            | ({
                relationTo: 'categories';
                value: number | Category;
              } | null)
            | ({
                relationTo: 'brands';
                value: number | Brand;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'post-categories';
                value: number | PostCategory;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  sections?:
    | (
        | FooterBrandBlock
        | FooterColumnBlock
        | FooterTextBlock
        | FooterContactBlock
        | FooterSocialBlock
        | FooterNewsletterBlock
      )[]
    | null;
  bottomBar?: {
    copyright?: string | null;
    legalLinks?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'products';
                  value: number | Product;
                } | null)
              | ({
                  relationTo: 'categories';
                  value: number | Category;
                } | null)
              | ({
                  relationTo: 'brands';
                  value: number | Brand;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null)
              | ({
                  relationTo: 'post-categories';
                  value: number | PostCategory;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterBrandBlock".
 */
export interface FooterBrandBlock {
  logo?: (number | null) | Media;
  tagline?: string | null;
  description?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'footerBrand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterColumnBlock".
 */
export interface FooterColumnBlock {
  title: string;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'products';
                value: number | Product;
              } | null)
            | ({
                relationTo: 'categories';
                value: number | Category;
              } | null)
            | ({
                relationTo: 'brands';
                value: number | Brand;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'post-categories';
                value: number | PostCategory;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'footerColumn';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterTextBlock".
 */
export interface FooterTextBlock {
  title?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'footerText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterContactBlock".
 */
export interface FooterContactBlock {
  title?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  workingHours?: string | null;
  mapLink?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'footerContact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterSocialBlock".
 */
export interface FooterSocialBlock {
  title?: string | null;
  profiles?:
    | {
        platform: 'facebook' | 'instagram' | 'linkedin' | 'tiktok' | 'x' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'footerSocial';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterNewsletterBlock".
 */
export interface FooterNewsletterBlock {
  heading: string;
  description?: string | null;
  buttonLabel?: string | null;
  privacyNote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'footerNewsletter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  heading?: string | null;
  logos?:
    | {
        image: number | Media;
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Koristi se kao sufiks u svim meta naslovima: „<naslov stranice> | <naziv sajta>".
   */
  siteName: string;
  /**
   * Bazni URL (bez završne kose crte). Koristi se za kanonske URL-ove, OG i sitemap.
   */
  siteUrl: string;
  defaultTitle?: string | null;
  defaultDescription?: string | null;
  defaultOgImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  topBar?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        subItems?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  promoBanner?:
    | T
    | {
        enabled?: T;
        text?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  sections?:
    | T
    | {
        footerBrand?: T | FooterBrandBlockSelect<T>;
        footerColumn?: T | FooterColumnBlockSelect<T>;
        footerText?: T | FooterTextBlockSelect<T>;
        footerContact?: T | FooterContactBlockSelect<T>;
        footerSocial?: T | FooterSocialBlockSelect<T>;
        footerNewsletter?: T | FooterNewsletterBlockSelect<T>;
      };
  bottomBar?:
    | T
    | {
        copyright?: T;
        legalLinks?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterBrandBlock_select".
 */
export interface FooterBrandBlockSelect<T extends boolean = true> {
  logo?: T;
  tagline?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterColumnBlock_select".
 */
export interface FooterColumnBlockSelect<T extends boolean = true> {
  title?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterTextBlock_select".
 */
export interface FooterTextBlockSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterContactBlock_select".
 */
export interface FooterContactBlockSelect<T extends boolean = true> {
  title?: T;
  phone?: T;
  email?: T;
  address?: T;
  workingHours?: T;
  mapLink?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterSocialBlock_select".
 */
export interface FooterSocialBlockSelect<T extends boolean = true> {
  title?: T;
  profiles?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterNewsletterBlock_select".
 */
export interface FooterNewsletterBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  buttonLabel?: T;
  privacyNote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  heading?: T;
  logos?:
    | T
    | {
        image?: T;
        name?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteUrl?: T;
  defaultTitle?: T;
  defaultDescription?: T;
  defaultOgImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}